### ISSUE TITLE
Post issue

### ISSUE THREAD

**Issue by SunilKumar32** [vinay1668/myclgapp#19]
![Screenshot_2022-04-16-13-06-32-690_com android chrome](https://user-images.githubusercontent.com/96165242/163669206-21f6660c-03c7-4dea-8e38-c284641662d4.jpg)

When ever i will post any type of data means it will be appearing in blank page. After refreshing the page itself data will be appearing.Otherwise it will not appear the data

**Comment by vinay1668** [comment]
I think this issue is because while registering, the branch is not updated in database. It shows empty string ("") instead of CSE/ECE/EEE. i will fix it as soon as possible

**Comment by SunilKumar32** [comment]
Make it as soon as possible
